create table gen_segment
(
    gen_segment_id   bigint generated by default as identity (maxvalue 99999999999999)
        primary key,
    gen_segment_name text                     not null
        constraint segname
            unique,
    display_name     text                     not null,
    is_item_segment  boolean,
    is_active        boolean,
    added_by         bigint                   not null,
    date_added       timestamp with time zone not null,
    updated_by       bigint,
    date_updated     timestamp with time zone
);

alter table gen_segment
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_segment to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_segment to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_segment to service_role;

