create table gen_bank_information
(
    gen_bank_information_id    bigint generated by default as identity
        primary key,
    banke_name                 text,
    ac_number                  text,
    swift_code                 text,
    routing_no                 text,
    bftin_no                   text,
    is_default                 boolean,
    attch_image                json,
    gen_general_information_id bigint                                 not null
        constraint fk_gen_bank_info_to_gen_genral_info
            references gen_supplier_information
            on delete cascade,
    added_by                   bigint                                 not null,
    updated_by                 bigint,
    date_added                 timestamp with time zone default now() not null,
    date_updated               timestamp with time zone default now()
);

alter table gen_bank_information
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_bank_information to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_bank_information to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_bank_information to service_role;

