create table gen_item_structure_group_sub_segment_mapping
(
    gen_item_structure_group_sub_segment_mapping_id bigint generated by default as identity
        primary key,
    gen_item_structure_group_sub_id                 bigint                   not null
        constraint fk_subgroup
            references gen_item_structure_group_sub,
    gen_segment_id                                  bigint                   not null
        constraint fk_segment
            references gen_segment,
    added_by                                        bigint                   not null,
    date_added                                      timestamp with time zone not null,
    updated_by                                      bigint,
    date_updated                                    timestamp with time zone
);

alter table gen_item_structure_group_sub_segment_mapping
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_item_structure_group_sub_segment_mapping to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_item_structure_group_sub_segment_mapping to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_item_structure_group_sub_segment_mapping to service_role;

