create table gen_season_event_config
(
    event_id       bigint generated by default as identity
        constraint tbl_season_month_config_pkey
            primary key,
    season_id      bigint
        constraint fk_season
            references gen_season,
    fiscal_year_id bigint
        constraint fk_fiscalyear
            references gen_fiscal_year,
    start_date     timestamp with time zone not null,
    start_month_id bigint                   not null,
    end_month_id   bigint                   not null,
    added_by       bigint                   not null,
    updated_by     bigint,
    date_added     timestamp with time zone not null,
    date_updated   timestamp,
    event_title    text,
    is_active      boolean,
    end_date       timestamp with time zone not null
);

alter table gen_season_event_config
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_season_event_config to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_season_event_config to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_season_event_config to service_role;

