create table gen_segment_detl
(
    gen_segment_detl_id bigint generated by default as identity
        primary key,
    gen_segment_id      bigint                   not null
        constraint fk_detl
            references gen_segment,
    segment_value       text                     not null,
    is_active           boolean,
    added_by            bigint                   not null,
    date_added          timestamp with time zone not null,
    updated_by          bigint,
    date_updated        timestamp with time zone
);

alter table gen_segment_detl
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_segment_detl to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_segment_detl to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_segment_detl to service_role;

