create table gen_team_members
(
    gen_team_members_id        bigint generated by default as identity
        constraint gen_team_members_id_pkey
            primary key,
    gen_team_group_id          bigint
        constraint fk_masterdet
            references gen_team_group,
    team_member_name           text,
    team_member_marketing_name text,
    team_member_marketing_code text,
    team_member_designation    text,
    phone_number               text,
    email                      text,
    office_extension_number    text,
    added_by                   bigint,
    updated_by                 bigint,
    date_added                 timestamp with time zone,
    date_updated               timestamp with time zone,
    photo                      text,
    user_id                    bigint
        constraint fk_user
            references owin_user
            on delete cascade
);

alter table gen_team_members
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_team_members to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_team_members to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_team_members to service_role;

