create table gen_fiscal_year
(
    fiscal_year_id bigint generated by default as identity
        constraint tbl_fiscal_year_pkey
            primary key,
    year_no        bigint    not null,
    year_name      text      not null,
    start_date     date      not null,
    end_date       date      not null,
    lock           boolean   not null,
    is_used        boolean   not null,
    added_by       bigint,
    date_added     timestamp not null,
    update_by      bigint,
    date_updated   timestamp
);

alter table gen_fiscal_year
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_fiscal_year to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_fiscal_year to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_fiscal_year to service_role;

