create table gen_map_supplier_branch
(
    gen_map_supplier_branch_id bigint generated by default as identity
        constraint gen_supplier_branch_pkey
            primary key,
    gen_branch_information_id  bigint                                 not null,
    gen_general_information_id bigint                                 not null
        constraint fk_gen_supplier_branch_to_general_info
            references gen_supplier_information
            on delete cascade,
    added_by                   bigint                                 not null,
    updated_by                 bigint,
    date_added                 timestamp with time zone default now() not null,
    date_updated               timestamp with time zone default now()
);

alter table gen_map_supplier_branch
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_map_supplier_branch to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_map_supplier_branch to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_map_supplier_branch to service_role;

