create table gen_contact_category
(
    gen_contact_category_id bigint generated by default as identity
        primary key,
    contact_category        text,
    added_by                bigint                                 not null,
    updated_by              bigint,
    date_added              timestamp with time zone default now() not null,
    date_updated            timestamp with time zone default now()
);

alter table gen_contact_category
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_contact_category to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_contact_category to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_contact_category to service_role;

