create sequence gen_general_information_gen_general_information_id_seq;

alter sequence gen_general_information_gen_general_information_id_seq owner to postgres;

alter sequence gen_general_information_gen_general_information_id_seq owned by gen_supplier_information.gen_supplier_information_id;

grant select, update, usage on sequence gen_general_information_gen_general_information_id_seq to anon;

grant select, update, usage on sequence gen_general_information_gen_general_information_id_seq to authenticated;

grant select, update, usage on sequence gen_general_information_gen_general_information_id_seq to service_role;

