create table gen_payment_method
(
    gen_payment_method_id bigint generated by default as identity
        primary key,
    payment_method        text,
    added_by              bigint                                 not null,
    updated_by            bigint,
    date_added            timestamp with time zone default now() not null,
    date_updated          timestamp with time zone default now()
);

alter table gen_payment_method
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_payment_method to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_payment_method to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_payment_method to service_role;

