create table gen_item_master
(
    gen_item_master_id          bigint generated by default as identity,
    item_name                   text                     not null,
    item_structure_group_id     bigint                   not null
        constraint itmgrp
            references gen_item_structure_group,
    item_structure_sub_group_id bigint                   not null
        constraint fk_itmsubgrp
            references gen_item_structure_group_sub,
    measurement_unit_detail_id  bigint                   not null
        constraint fk_unit
            references gen_measurement_unit_detail,
    segment_det1_id             bigint
        constraint fk_sg1
            references gen_segment_detl,
    segment_det2_id             bigint
        constraint fk_sg2
            references gen_segment_detl,
    segment_det3_id             bigint
        constraint fk_sg3
            references gen_segment_detl,
    segment_det4_id             bigint
        constraint fk_sg4
            references gen_segment_detl,
    segment_det5_id             bigint
        constraint fk_sg5
            references gen_segment_detl,
    segment_det6_id             bigint
        constraint fk_sg6
            references gen_segment_detl,
    segment_det7_id             bigint
        constraint fk_sg7
            references gen_segment_detl,
    segment_det8_id             bigint
        constraint fk_sg8
            references gen_segment_detl,
    segment_det9_id             bigint
        constraint fk_sg9
            references gen_segment_detl,
    segment_det10_id            bigint
        constraint fk_sg10
            references gen_segment_detl,
    segment_det11_id            bigint
        constraint fk_sg11
            references gen_segment_detl,
    segment_det12_id            bigint
        constraint fk_sg12
            references gen_segment_detl,
    segment_det13_id            bigint
        constraint fk_sg13
            references gen_segment_detl,
    segment_det14_id            bigint
        constraint fk_sg14
            references gen_segment_detl,
    segment_det15_id            bigint
        constraint fk_sg15
            references gen_segment_detl,
    remarks                     text,
    added_by                    bigint                   not null,
    date_added                  timestamp with time zone not null,
    updated_by                  bigint,
    date_updated                timestamp with time zone,
    primary key (measurement_unit_detail_id, item_structure_group_id, item_structure_sub_group_id, gen_item_master_id)
);

alter table gen_item_master
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_item_master to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_item_master to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_item_master to service_role;

