create table gen_supplier_information
(
    gen_supplier_information_id bigint generated by default as identity
        constraint gen_general_information_pkey
            primary key,
    contact_code                text,
    name                        text,
    short_name                  text,
    display_code                text,
    email                       varchar,
    office_address              text,
    factory_address             text,
    fax_no                      text,
    gen_contact_category_id     bigint,
    contact_person              text,
    country                     text,
    city                        text,
    agent_name                  text,
    gen_business_type_id        bigint,
    geographical_location       text,
    active                      boolean,
    added_by                    bigint                                 not null,
    updated_by                  bigint,
    date_added                  timestamp with time zone default now() not null,
    date_updated                timestamp with time zone default now()
);

alter table gen_supplier_information
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_supplier_information to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_supplier_information to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_supplier_information to service_role;

