create table gen_mode_of_transaction
(
    gen_mode_of_transaction_id bigint generated by default as identity
        primary key,
    mode_of_transaction        text,
    added_by                   bigint                                 not null,
    updated_by                 bigint,
    date_added                 timestamp with time zone default now() not null,
    date_updated               timestamp with time zone default now()
);

alter table gen_mode_of_transaction
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_mode_of_transaction to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_mode_of_transaction to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_mode_of_transaction to service_role;

