create table gen_credit_period
(
    gen_credit_period_id bigint generated by default as identity
        primary key,
    credit_period        text,
    added_by             bigint                                 not null,
    updated_by           bigint,
    date_added           timestamp with time zone default now() not null,
    date_updated         timestamp with time zone default now()
);

alter table gen_credit_period
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_credit_period to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_credit_period to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_credit_period to service_role;

