create table " gen_map_supplier_mode_of_transaction"
(
    gen_map_supplier_mode_of_transaction_id bigint generated by default as identity
        constraint gen_supplier_mode_of_transaction_pkey
            primary key,
    gen_mode_of_transaction_id              bigint                                 not null
        constraint fk_gen_supp_mod_tran_to_gen_mod_of_tran
            references gen_mode_of_transaction
            on delete cascade,
    gen_financial_information_id            bigint                                 not null
        constraint fk_gen_supp_mod_tran_to_gen_fin_info
            references gen_supplier_financial_information
            on delete cascade,
    added_by                                bigint                                 not null,
    updated_by                              bigint,
    date_added                              timestamp with time zone default now() not null,
    date_updated                            timestamp with time zone default now()
);

alter table " gen_map_supplier_mode_of_transaction"
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on " gen_map_supplier_mode_of_transaction" to anon;

grant delete, insert, references, select, trigger, truncate, update on " gen_map_supplier_mode_of_transaction" to authenticated;

grant delete, insert, references, select, trigger, truncate, update on " gen_map_supplier_mode_of_transaction" to service_role;

