create table gen_department
(
    department_id          bigint generated by default as identity
        constraint "Security.department_pkey"
            primary key,
    department_code        varchar   not null,
    department_name        varchar   not null,
    department_description text,
    is_default             boolean,
    department_logo_path   varchar,
    sequence_no            smallint,
    added_by               bigint default 0,
    updated_by             bigint,
    date_added             timestamp not null,
    date_updated           timestamp
);

alter table gen_department
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_department to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_department to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_department to service_role;

