create table gen_map_supplier_inco_term
(
    gen_map_supplier_inco_term_id bigint generated by default as identity
        constraint gen_supplier_inco_term_pkey
            primary key,
    gen_inco_term_id              bigint                                 not null
        constraint fk_supp_inco_term_to_gen_inco_term
            references gen_inco_term
            on delete cascade,
    gen_financial_information_id  bigint                                 not null
        constraint fk_supp_inco_term_to_gen_fin_info
            references gen_supplier_financial_information
            on delete cascade,
    added_by                      bigint                                 not null,
    updated_by                    bigint,
    date_added                    timestamp with time zone default now() not null,
    date_updated                  timestamp with time zone default now()
);

alter table gen_map_supplier_inco_term
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_map_supplier_inco_term to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_map_supplier_inco_term to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_map_supplier_inco_term to service_role;

