create table gen_branch_information
(
    gen_branch_information_id bigint generated by default as identity
        primary key,
    branch_name               text,
    branch_address            text,
    added_by                  bigint                                 not null,
    updated_by                bigint,
    date_added                timestamp with time zone default now() not null,
    date_updated              timestamp with time zone default now()
);

alter table gen_branch_information
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_branch_information to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_branch_information to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_branch_information to service_role;

