create table gen_business_type
(
    gen_business_type_id bigint generated by default as identity
        primary key,
    business_type        text,
    added_by             bigint                                 not null,
    updated_by           bigint,
    date_added           timestamp with time zone default now() not null,
    date_updated         timestamp with time zone default now()
);

alter table gen_business_type
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_business_type to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_business_type to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_business_type to service_role;

