create table gen_team_group
(
    gen_team_group_id   bigint generated by default as identity
        constraint gen_team_group_id_pkey
            primary key,
    department_id       bigint,
    team_group_name     text,
    team_head_name      text,
    team_head_id_number text,
    added_by            bigint,
    updated_by          bigint,
    date_added          timestamp with time zone,
    date_updated        timestamp with time zone
);

alter table gen_team_group
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_team_group to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_team_group to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_team_group to service_role;

