create table " gen_map_supplier_payment_method"
(
    gen_map_supplier_payment_method_id bigint generated by default as identity
        constraint gen_supplier_payment_method_pkey
            primary key,
    gen_payment_method_id              bigint                                 not null
        constraint fk_gen_supp_meth_to_gen_pay_meth
            references gen_payment_method
            on delete cascade,
    gen_financial_information_id       bigint                                 not null
        constraint fk_gen_supp_meth_to_gen_fin_info
            references gen_supplier_financial_information
            on delete cascade,
    added_by                           bigint                                 not null,
    updated_by                         bigint,
    date_added                         timestamp with time zone default now() not null,
    date_updated                       timestamp with time zone default now()
);

alter table " gen_map_supplier_payment_method"
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on " gen_map_supplier_payment_method" to anon;

grant delete, insert, references, select, trigger, truncate, update on " gen_map_supplier_payment_method" to authenticated;

grant delete, insert, references, select, trigger, truncate, update on " gen_map_supplier_payment_method" to service_role;

