create table gen_legal_information
(
    gen_legal_information_id   bigint generated by default as identity
        primary key,
    vat_bin_number             text,
    vat_bin_number_start_date  timestamp with time zone default now(),
    vat_bin_number_expire_date timestamp with time zone default now(),
    vat_bin_documnet           json,
    tin_number                 text,
    tin_document               json,
    trade_license              text,
    trade_license_start_date   timestamp with time zone default now(),
    trade_license_expire_date  timestamp with time zone default now(),
    trade_license_document     json,
    gen_general_information_id bigint
        constraint fk_ee
            references gen_supplier_information,
    added_by                   bigint                                 not null,
    updated_by                 bigint,
    date_added                 timestamp with time zone default now() not null,
    date_updated               timestamp with time zone default now()
);

alter table gen_legal_information
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_legal_information to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_legal_information to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_legal_information to service_role;

