create table gen_garment_part
(
    gen_garment_part_id bigint generated by default as identity
        primary key,
    garment_part_name   text,
    short_code          text,
    multiplier          bigint,
    added_by            bigint    not null,
    updated_by          bigint,
    date_added          timestamp not null,
    date_updated        timestamp
);

alter table gen_garment_part
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_garment_part to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_garment_part to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_garment_part to service_role;

