create table gen_process_master
(
    gen_process_master_id      bigint generated by default as identity (maxvalue 99999999999999)
        primary key,
    process_name               text                     not null
        constraint process_name
            unique,
    has_sub_process            boolean,
    has_embellishment          boolean,
    measurement_unit_detail_id bigint,
    added_by                   bigint                   not null,
    date_added                 timestamp with time zone not null,
    updated_by                 bigint,
    date_updated               timestamp with time zone
);

alter table gen_process_master
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_process_master to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_process_master to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_process_master to service_role;

