create table gen_season
(
    season_id    bigint generated by default as identity
        constraint tbl_season_master_pkey
            primary key,
    season_name  text      not null,
    short_name   text      not null,
    is_active    boolean,
    added_by     bigint    not null,
    date_added   timestamp not null,
    updated_by   bigint,
    date_updated timestamp,
    sequence     bigint
);

alter table gen_season
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_season to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_season to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_season to service_role;

