create table gen_process_master_detail
(
    gen_process_master_detail_id bigint generated by default as identity (maxvalue 99999999999999)
        primary key,
    gen_process_master_id        bigint                   not null
        constraint fk_detl
            references gen_process_master
            on delete cascade,
    sub_process_name             text                     not null,
    added_by                     bigint                   not null,
    date_added                   timestamp with time zone not null,
    updated_by                   bigint,
    date_updated                 timestamp with time zone
);

alter table gen_process_master_detail
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_process_master_detail to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_process_master_detail to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_process_master_detail to service_role;

