create table gen_calculation_of_tenure
(
    gen_calculation_of_tenure_id bigint generated by default as identity
        primary key,
    calculation_of_tenure        text,
    added_by                     bigint                                 not null,
    updated_by                   bigint,
    date_added                   timestamp with time zone default now() not null,
    date_updated                 timestamp with time zone default now()
);

alter table gen_calculation_of_tenure
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_calculation_of_tenure to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_calculation_of_tenure to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_calculation_of_tenure to service_role;

