create table gen_supplier_financial_information
(
    gen_suplier_financial_information_id bigint generated by default as identity
        constraint gen_financial_information_pkey
            primary key,
    gen_credit_period_id                 bigint,
    gen_calculation_of_tenure_id         bigint,
    gen_general_information_id           bigint
        constraint fk_gen_fin_info_to_gen_info
            references gen_supplier_information
            on delete cascade,
    added_by                             bigint                                 not null,
    updated_by                           bigint,
    date_added                           timestamp with time zone default now() not null,
    date_updated                         timestamp with time zone default now()
);

alter table gen_supplier_financial_information
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_supplier_financial_information to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_supplier_financial_information to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_supplier_financial_information to service_role;

