create table gen_outlet
(
    outlet_id          bigint generated by default as identity
        constraint "Security.outlet_pkey"
            primary key,
    outlet_code        text,
    outlet_name        varchar   not null,
    outlet_description varchar,
    district_id        bigint,
    division_id        bigint,
    outlet_address     varchar,
    is_active          boolean,
    outlet_logo_path   varchar,
    sequence_no        bigint,
    added_by           bigint    not null,
    updated_by         bigint,
    date_added         timestamp not null,
    date_updated       timestamp
);

alter table gen_outlet
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_outlet to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_outlet to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_outlet to service_role;

