create table gen_concern_person_information
(
    gen_concern_person_information_id bigint generated by default as identity
        primary key,
    name                              text,
    designation                       text,
    phone_no                          text,
    fax                               text,
    email                             varchar,
    address                           text,
    added_by                          bigint                                 not null,
    updated_by                        bigint,
    date_added                        timestamp with time zone default now() not null,
    date_updated                      timestamp with time zone default now()
);

alter table gen_concern_person_information
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on gen_concern_person_information to anon;

grant delete, insert, references, select, trigger, truncate, update on gen_concern_person_information to authenticated;

grant delete, insert, references, select, trigger, truncate, update on gen_concern_person_information to service_role;

