create table login_user_attached_with_group_user
(
    child_id     bigint generated by default as identity
        constraint "Security.LoginUserAttachedWithGroupUser_pkey"
            primary key,
    user_code    bigint not null,
    group_code   bigint not null,
    added_by     bigint not null,
    updated_by   bigint,
    date_added   timestamp,
    date_updated timestamp
);

alter table login_user_attached_with_group_user
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on login_user_attached_with_group_user to anon;

grant delete, insert, references, select, trigger, truncate, update on login_user_attached_with_group_user to authenticated;

grant delete, insert, references, select, trigger, truncate, update on login_user_attached_with_group_user to service_role;

