create table menu_action
(
    menu_action_id bigint generated by default as identity
        constraint owin_formaction_pkey
            primary key,
    menu_id        bigint
        constraint fk_menu
            references menu
            on delete cascade,
    action_url     text      not null,
    method_name    text      not null,
    added_by       bigint    not null,
    updated_by     bigint,
    date_added     timestamp not null,
    date_updated   timestamp
);

alter table menu_action
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on menu_action to anon;

grant delete, insert, references, select, trigger, truncate, update on menu_action to authenticated;

grant delete, insert, references, select, trigger, truncate, update on menu_action to service_role;

