create table owin_role_permission
(
    role_permission_id bigint generated by default as identity (maxvalue 2147483647),
    role_id            bigint    not null,
    menu_action_id     bigint    not null,
    menu_id            bigint    not null,
    is_permitted       boolean   not null,
    added_by           bigint    not null,
    updated_by         bigint,
    date_added         timestamp not null,
    date_updated       timestamp
);

alter table owin_role_permission
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on owin_role_permission to anon;

grant delete, insert, references, select, trigger, truncate, update on owin_role_permission to authenticated;

grant delete, insert, references, select, trigger, truncate, update on owin_role_permission to service_role;

