create table owin_role
(
    owin_role_id bigint generated by default as identity
        primary key,
    role_name    text      not null,
    added_by     bigint    not null,
    updated_by   bigint,
    date_added   timestamp not null,
    date_updated timestamp
);

alter table owin_role
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on owin_role to anon;

grant delete, insert, references, select, trigger, truncate, update on owin_role to authenticated;

grant delete, insert, references, select, trigger, truncate, update on owin_role to service_role;

