create table owin_userrole
(
    userroleid   bigint generated by default as identity,
    userid       bigint    not null
        primary key,
    roleid       bigint    not null,
    isenable     boolean   not null,
    added_by     bigint    not null,
    updated_by   bigint,
    date_added   timestamp not null,
    date_updated timestamp
);

alter table owin_userrole
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on owin_userrole to anon;

grant delete, insert, references, select, trigger, truncate, update on owin_userrole to authenticated;

grant delete, insert, references, select, trigger, truncate, update on owin_userrole to service_role;

