create table owin_user
(
    userid            bigint generated by default as identity (maxvalue 2147483647)
        constraint loginuser_pkey
            primary key,
    name              varchar   not null,
    user_name         varchar   not null,
    password          varchar   not null,
    email             varchar,
    email_password    varchar,
    is_super_user     boolean,
    is_admin          boolean,
    is_active         boolean   not null,
    is_loggedin       boolean,
    logon_time        timestamp,
    employee_code     bigint,
    added_by          bigint    not null,
    updated_by        bigint,
    date_added        timestamp not null,
    date_updated      timestamp,
    role_id           bigint,
    gen_team_group_id bigint
);

alter table owin_user
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on owin_user to anon;

grant delete, insert, references, select, trigger, truncate, update on owin_user to authenticated;

grant delete, insert, references, select, trigger, truncate, update on owin_user to service_role;

