create table security_rule_menu
(
    master_id          bigint generated by default as identity
        constraint "Security.SecurityRuleMenu_pkey"
            primary key,
    menu_id            bigint not null,
    security_rule_code bigint,
    can_select         boolean,
    can_insert         boolean,
    can_update         boolean,
    can_delete         boolean,
    added_by           bigint,
    updated_by         bigint,
    date_added         timestamp,
    date_updated       timestamp
);

alter table security_rule_menu
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on security_rule_menu to anon;

grant delete, insert, references, select, trigger, truncate, update on security_rule_menu to authenticated;

grant delete, insert, references, select, trigger, truncate, update on security_rule_menu to service_role;

