create table style_item_origin
(
    style_item_origin_id   bigint generated by default as identity
        constraint tbl_style_item_origin_pkey
            primary key,
    style_item_origin_name text      not null,
    is_active              boolean   not null,
    added_by               bigint    not null,
    date_added             timestamp not null,
    updated_by             bigint,
    date_updated           timestamp
);

alter table style_item_origin
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on style_item_origin to anon;

grant delete, insert, references, select, trigger, truncate, update on style_item_origin to authenticated;

grant delete, insert, references, select, trigger, truncate, update on style_item_origin to service_role;

