create table style_master_category
(
    style_master_category_id bigint generated by default as identity
        constraint tbl_style_master_category_pkey
            primary key,
    master_category_name     varchar   not null,
    is_active                boolean   not null,
    added_by                 bigint    not null,
    date_added               timestamp not null,
    updated_by               bigint,
    date_updated             timestamp
);

alter table style_master_category
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on style_master_category to anon;

grant delete, insert, references, select, trigger, truncate, update on style_master_category to authenticated;

grant delete, insert, references, select, trigger, truncate, update on style_master_category to service_role;

