create table style_garment_part
(
    style_garment_part_id bigint generated by default as identity
        constraint tbl_style_garment_part_pkey
            primary key,
    garment_part_name     text not null,
    short_name            text not null,
    is_active             boolean,
    added_by              bigint,
    date_added            timestamp with time zone,
    updated_by            bigint,
    date_updated          timestamp with time zone
);

alter table style_garment_part
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on style_garment_part to anon;

grant delete, insert, references, select, trigger, truncate, update on style_garment_part to authenticated;

grant delete, insert, references, select, trigger, truncate, update on style_garment_part to service_role;

