create table style_category
(
    style_category_id        bigint generated by default as identity
        constraint tbl_style_category_pkey
            primary key,
    style_master_category_id bigint    not null,
    style_category_name      varchar   not null,
    style_category_code      varchar   not null,
    has_sleeve               boolean   not null,
    has_hoody                boolean   not null,
    has_length               boolean   not null,
    has_fit                  boolean   not null,
    is_active                boolean   not null,
    added_by                 bigint    not null,
    date_added               timestamp not null,
    updated_by               bigint,
    date_updated             timestamp
);

alter table style_category
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on style_category to anon;

grant delete, insert, references, select, trigger, truncate, update on style_category to authenticated;

grant delete, insert, references, select, trigger, truncate, update on style_category to service_role;

