create table style_product_type
(
    style_product_type_id   bigint generated by default as identity
        constraint tbl_style_product_type_pkey
            primary key,
    style_product_type_name varchar   not null,
    added_by                bigint    not null,
    date_added              timestamp not null,
    updated_by              bigint,
    date_updated            timestamp
);

alter table style_product_type
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on style_product_type to anon;

grant delete, insert, references, select, trigger, truncate, update on style_product_type to authenticated;

grant delete, insert, references, select, trigger, truncate, update on style_product_type to service_role;

