create table style_product_size_group
(
    style_product_size_group_id   bigint generated by default as identity
        constraint tbl_style_product_size_pkey
            primary key,
    style_product_size_group_name text                     not null,
    added_by                      bigint                   not null,
    date_added                    timestamp with time zone not null,
    updated_by                    bigint,
    date_updated                  timestamp with time zone,
    is_separate_price             boolean
);

alter table style_product_size_group
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on style_product_size_group to anon;

grant delete, insert, references, select, trigger, truncate, update on style_product_size_group to authenticated;

grant delete, insert, references, select, trigger, truncate, update on style_product_size_group to service_role;

