create table style_item_product
(
    style_item_product_id       bigint generated by default as identity
        constraint tbl_style_item_product_pkey
            primary key,
    style_item_product_name     varchar                  not null,
    style_item_type_id          bigint                   not null
        constraint fk_itemtype
            references style_item_type,
    style_product_type_id       bigint                   not null
        constraint fk_prodtype
            references style_product_type,
    style_item_origin_id        bigint                   not null
        constraint fk_origin
            references style_item_origin,
    style_gender_id             bigint                   not null
        constraint fk_gender
            references style_gender,
    style_master_category_id    bigint                   not null
        constraint fk_mastercatgory
            references style_master_category,
    added_by                    bigint                   not null,
    date_added                  timestamp with time zone not null,
    updated_by                  bigint,
    date_updated                timestamp with time zone,
    fiscal_year_id              bigint                   not null
        constraint fk_year
            references gen_fiscal_year,
    style_product_size_group_id bigint                   not null
        constraint fk_size_ggrp
            references style_product_size_group
);

alter table style_item_product
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on style_item_product to anon;

grant delete, insert, references, select, trigger, truncate, update on style_item_product to authenticated;

grant delete, insert, references, select, trigger, truncate, update on style_item_product to service_role;

