create table style_item_type
(
    style_item_type_id   bigint generated by default as identity
        constraint tbl_style_item_type_pkey
            primary key,
    style_item_type_name varchar   not null,
    style_item_type_code varchar,
    is_active            boolean   not null,
    added_by             bigint    not null,
    date_added           timestamp not null,
    updated_by           bigint,
    date_updated         timestamp
);

alter table style_item_type
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on style_item_type to anon;

grant delete, insert, references, select, trigger, truncate, update on style_item_type to authenticated;

grant delete, insert, references, select, trigger, truncate, update on style_item_type to service_role;

