create table style_product_size_group_details
(
    style_product_size_group_detid bigint generated by default as identity
        constraint tbl_style_product_det_size_pkey
            primary key,
    style_product_size_group_id    bigint                   not null
        constraint fk_master_det
            references style_product_size_group,
    style_product_size             text                     not null,
    added_by                       bigint                   not null,
    date_added                     timestamp with time zone not null,
    updated_by                     bigint,
    date_updated                   timestamp with time zone
);

alter table style_product_size_group_details
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on style_product_size_group_details to anon;

grant delete, insert, references, select, trigger, truncate, update on style_product_size_group_details to authenticated;

grant delete, insert, references, select, trigger, truncate, update on style_product_size_group_details to service_role;

