create table style_product_unit
(
    style_product_unit_id   bigint generated by default as identity
        constraint tbl_style_product_unit_pkey
            primary key,
    style_product_unit_name varchar   not null,
    added_by                bigint    not null,
    date_added              timestamp not null,
    updated_by              bigint,
    date_updated            timestamp,
    unit_type               bigint
);

alter table style_product_unit
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on style_product_unit to anon;

grant delete, insert, references, select, trigger, truncate, update on style_product_unit to authenticated;

grant delete, insert, references, select, trigger, truncate, update on style_product_unit to service_role;

