create table style_label
(
    style_label_id    bigint generated by default as identity
        constraint tbl_style_label_pkey
            primary key,
    style_label_name  varchar   not null,
    short_name        varchar   not null,
    label_code        varchar,
    label_description varchar,
    is_active         boolean,
    added_by          bigint    not null,
    date_added        timestamp not null,
    updated_by        bigint,
    date_updated      timestamp
);

alter table style_label
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on style_label to anon;

grant delete, insert, references, select, trigger, truncate, update on style_label to authenticated;

grant delete, insert, references, select, trigger, truncate, update on style_label to service_role;

