create table tran_scm_po_for_pr
(
    po_for_pr_id bigint generated by default as identity (maxvalue 2147483647),
    po_id        bigint not null,
    pr_id        bigint not null
);

alter table tran_scm_po_for_pr
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_scm_po_for_pr to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_scm_po_for_pr to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_scm_po_for_pr to service_role;

