create table tran_va_plan_events
(
    tran_va_plan_event_id    bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    tran_va_plan_id          bigint
        constraint fk_detls
            references tran_va_plan
            on delete cascade,
    tran_range_plan_event_id bigint
        constraint fk_event
            references tran_range_plan_events,
    is_finalised             boolean,
    added_by                 bigint                                 not null,
    updated_by               bigint,
    date_added               timestamp with time zone default now() not null,
    date_updated             timestamp with time zone,
    plan_detl_details        json
);

alter table tran_va_plan_events
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_va_plan_events to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_va_plan_events to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_va_plan_events to service_role;

