create table tran_bp_year
(
    tran_bp_year_id bigint generated by default as identity
        primary key,
    fiscal_year_id  bigint
        references gen_fiscal_year,
    gross_sales     numeric,
    added_by        bigint                                 not null,
    updated_by      bigint,
    date_added      timestamp with time zone default now() not null,
    date_updated    timestamp with time zone default now(),
    is_approved     boolean,
    approved_by     bigint,
    approve_date    timestamp with time zone,
    approve_remarks text,
    remarks         text,
    is_submitted    boolean,
    event_list_json json
);

alter table tran_bp_year
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_bp_year to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_bp_year to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_bp_year to service_role;

