create table tran_pre_costing_item_detail
(
    tran_pre_costing_item_detail_id bigint generated by default as identity
        primary key,
    tran_pre_costing_id             bigint                   not null
        constraint fk_detl
            references tran_pre_costing
            on delete cascade,
    gen_item_structure_group_sub_id bigint                   not null
        constraint fk_subgroup
            references gen_item_structure_group_sub,
    segment_det1_id                 bigint
        constraint fk_segmnt_detl
            references gen_segment_detl,
    segment_det2_id                 bigint
        constraint fk_segmnt_detl2
            references gen_segment_detl,
    segment_det3_id                 bigint
        constraint fk_segmnt_detl3
            references gen_segment_detl,
    segment_det4_id                 bigint
        constraint fk_segmnt_detl4
            references gen_segment_detl,
    segment_det5_id                 bigint
        constraint fk_segmnt_detl5
            references gen_segment_detl,
    segment_det6_id                 bigint
        constraint fk_segmnt_detl6
            references gen_segment_detl,
    segment_det7_id                 bigint
        constraint fk_segmnt_detl7
            references gen_segment_detl,
    segment_det8_id                 bigint
        constraint fk_segmnt_detl8
            references gen_segment_detl,
    segment_det9_id                 bigint
        constraint fk_segmnt_detl9
            references gen_segment_detl,
    segment_det10_id                bigint
        constraint fk_segmnt_detl10
            references gen_segment_detl,
    segment_det11_id                bigint
        constraint fk_segmnt_detl11
            references gen_segment_detl,
    segment_det12_id                bigint
        constraint fk_segmnt_detl12
            references gen_segment_detl,
    segment_det13_id                bigint
        constraint fk_segmnt_detl13
            references gen_segment_detl,
    segment_det14_id                bigint
        constraint fk_segmnt_detl14
            references gen_segment_detl,
    segment_det15_id                bigint
        constraint fk_segmnt_detl15
            references gen_segment_detl,
    segment_det1_text               text,
    segment_det2_text               text,
    segment_det3_text               text,
    segment_det4_text               text,
    segment_det5_text               text,
    segment_det6_text               text,
    segment_det7_text               text,
    segment_det8_text               text,
    segment_det9_text               text,
    segment_det10_text              text,
    segment_det11_text              text,
    segment_det12_text              text,
    segment_det13_text              text,
    segment_det14_text              text,
    segment_det15_text              text,
    measurement_unit_detail_id      bigint                   not null,
    order_quantity                  numeric                  not null,
    wastage                         numeric,
    total_order_quantity            numeric                  not null,
    price_per_unit                  numeric,
    total_price                     numeric,
    remarks                         text,
    added_by                        bigint                   not null,
    date_added                      timestamp with time zone not null,
    updated_by                      bigint,
    date_updated                    timestamp with time zone
);

alter table tran_pre_costing_item_detail
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_pre_costing_item_detail to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_pre_costing_item_detail to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_pre_costing_item_detail to service_role;

