create table tran_range_plan_events
(
    tran_range_plan_event_id  bigint generated by default as identity
        primary key,
    range_plan_id             bigint
        constraint fk_range_plan
            references tran_range_plan
            on delete cascade,
    tran_bp_event_id          bigint
        constraint fk_event
            references tran_bp_event,
    total_mrp_value           numeric,
    total_cpu_value           numeric,
    total_range_plan_quantity bigint,
    is_finalized              boolean,
    added_by                  bigint                   not null,
    updated_by                bigint,
    date_added                timestamp with time zone not null,
    date_updated              timestamp with time zone
);

alter table tran_range_plan_events
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_range_plan_events to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_range_plan_events to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_range_plan_events to service_role;

