create table tran_range_plan_details_size
(
    range_plan_detail_size_id         bigint generated by default as identity
        primary key,
    range_plan_detail_id              bigint                   not null
        constraint fk_plandetl
            references tran_range_plan_details
            on delete cascade,
    style_product_size_group_detid    bigint                   not null
        constraint fk_detl_size
            references style_product_size_group_details,
    size_quantity                     bigint                   not null,
    size_per_pc_mrp_value             numeric,
    added_by                          bigint                   not null,
    updated_by                        bigint,
    date_added                        timestamp with time zone not null,
    date_updated                      timestamp with time zone,
    size_per_pc_cpu_value             numeric,
    range_plan_details_size_list_json json
);

alter table tran_range_plan_details_size
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_range_plan_details_size to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_range_plan_details_size to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_range_plan_details_size to service_role;

