create table tran_scm_fabric_po
(
    po_id               bigint generated by default as identity (maxvalue 2147483647),
    po_no               text,
    po_date             timestamp with time zone,
    delivery_start_date timestamp with time zone,
    delivery_end_date   timestamp with time zone,
    supplier_id         bigint                                 not null,
    delivery_unit       bigint                                 not null,
    delivery_address    bigint                                 not null,
    currency_id         bigint                                 not null,
    documents           json,
    terms_conditions    json,
    is_submitted        boolean,
    status              integer                                not null,
    added_by            bigint                                 not null,
    updated_by          bigint,
    date_added          timestamp with time zone default now() not null,
    date_updated        timestamp with time zone
);

alter table tran_scm_fabric_po
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_scm_fabric_po to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_scm_fabric_po to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_scm_fabric_po to service_role;

