create table tran_designer_review
(
    tran_designer_review_id           bigint generated by default as identity (maxvalue 2147483647)
        constraint tran_designer_review_id_pkey
            primary key,
    tran_pre_costing_id               bigint                                 not null
        constraint fk
            references tran_pre_costing,
    no_review                         bigint,
    no_confirmation                   bigint,
    no_confirmation_with_modification bigint,
    no_of_not_confirmed               bigint,
    status                            bigint,
    remarks                           text,
    is_submitted                      boolean,
    is_approved                       boolean,
    approved_by                       bigint,
    approve_date                      timestamp with time zone,
    approve_remarks                   text,
    added_by                          bigint                                 not null,
    updated_by                        bigint,
    date_added                        timestamp with time zone default now() not null,
    date_updated                      timestamp with time zone default now(),
    "Document"                        json
);

alter table tran_designer_review
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_designer_review to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_designer_review to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_designer_review to service_role;

