create table tran_va_plan_detl_style_color
(
    tran_va_plan_detl_style_color_id bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    tran_va_plan_detl_style_id       bigint                                 not null
        constraint fk_style
            references tran_va_plan_detl_style
            on delete cascade,
    color_code                       text                                   not null,
    style_color_quantity             bigint                                 not null,
    added_by                         bigint                                 not null,
    updated_by                       bigint,
    date_added                       timestamp with time zone default now() not null,
    date_updated                     timestamp with time zone,
    style_color_size_details         json
);

alter table tran_va_plan_detl_style_color
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_va_plan_detl_style_color to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_va_plan_detl_style_color to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_va_plan_detl_style_color to service_role;

