create table tran_va_plan_detl_style
(
    tran_va_plan_detl_style_id         bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    tran_va_plan_detl_id               bigint                                 not null
        constraint fk_plandetl
            references tran_va_plan_detl
            on delete cascade,
    style_code                         text                                   not null,
    style_quantity                     bigint                                 not null,
    no_of_color                        bigint                                 not null,
    color_code_gen                     text                                   not null,
    added_by                           bigint                                 not null,
    updated_by                         bigint,
    date_added                         timestamp with time zone default now() not null,
    date_updated                       timestamp with time zone,
    style_embellishment_ids            json,
    designer_member_id                 bigint,
    style_item_product_sub_category_id bigint
        constraint sub_categoryid
            references style_item_product_sub_category,
    style_color_details                json,
    is_delete                          integer
);

alter table tran_va_plan_detl_style
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_va_plan_detl_style to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_va_plan_detl_style to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_va_plan_detl_style to service_role;

