create table tran_sample_order_subgroup
(
    tran_sample_order_subgroup_id   bigint generated by default as identity
        primary key,
    tran_sample_order_id            bigint                   not null
        constraint fk_det
            references tran_sample_order
            on delete cascade,
    gen_item_structure_group_sub_id bigint                   not null
        constraint fk_subcat
            references gen_item_structure_group_sub
            on delete cascade,
    remarks                         text,
    added_by                        bigint                   not null,
    date_added                      timestamp with time zone not null,
    updated_by                      bigint,
    date_updated                    timestamp with time zone
);

alter table tran_sample_order_subgroup
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_sample_order_subgroup to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_sample_order_subgroup to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_sample_order_subgroup to service_role;

