create table tran_sample_order_detl
(
    tran_sample_order_detl_id      bigint generated by default as identity
        primary key,
    tran_sample_order_id           bigint
        constraint fk_detl
            references tran_sample_order
            on delete cascade,
    color_code                     text,
    style_product_size_group_detid bigint
        constraint fk_size
            references style_product_size_group_details,
    order_quantity                 bigint,
    style_product_unit_id          bigint
        constraint fk_unit
            references style_product_unit,
    remarks                        text,
    added_by                       bigint                   not null,
    date_added                     timestamp with time zone not null,
    updated_by                     bigint,
    date_updated                   timestamp with time zone
);

alter table tran_sample_order_detl
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_sample_order_detl to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_sample_order_detl to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_sample_order_detl to service_role;

