create table tran_pre_costing_item_embellishment_detail
(
    tran_pre_costing_item_embellishment_detail_id bigint generated by default as identity
        constraint tran_pre_costing_item_embellishment_detail_id_pkey
            primary key,
    tran_pre_costing_id                           bigint                   not null
        constraint master_det
            references tran_pre_costing
            on delete cascade,
    style_embellishment_id                        bigint,
    measurement_unit_detail_id                    bigint
        constraint fk_measurement
            references gen_measurement_unit_detail,
    order_quantity                                numeric                  not null,
    wastage                                       numeric,
    total_order_quantity                          numeric                  not null,
    price_per_unit                                numeric,
    total_price                                   numeric,
    remarks                                       text,
    added_by                                      bigint                   not null,
    date_added                                    timestamp with time zone not null,
    updated_by                                    bigint,
    date_updated                                  timestamp with time zone
);

alter table tran_pre_costing_item_embellishment_detail
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_pre_costing_item_embellishment_detail to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_pre_costing_item_embellishment_detail to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_pre_costing_item_embellishment_detail to service_role;

