create table tran_va_plan_detl
(
    tran_va_plan_detl_id  bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    tran_va_plan_event_id bigint                                 not null
        constraint fk_event_ids
            references tran_va_plan_events
            on delete cascade,
    range_plan_detail_id  bigint                                 not null
        constraint fk_rangeplanid
            references tran_range_plan_details,
    style_item_product_id bigint                                 not null
        constraint fk_product
            references style_item_product,
    no_of_style           bigint                                 not null,
    style_code_gen        text                                   not null,
    added_by              bigint                                 not null,
    updated_by            bigint,
    date_added            timestamp with time zone default now() not null,
    date_updated          timestamp with time zone,
    style_details         json
);

alter table tran_va_plan_detl
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_va_plan_detl to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_va_plan_detl to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_va_plan_detl to service_role;

