create table tran_range_plan_details
(
    range_plan_detail_id              bigint generated by default as identity
        primary key,
    range_plan_id                     bigint                   not null
        constraint fk_masterdet
            references tran_range_plan
            on delete cascade,
    tran_bp_event_id                  bigint                   not null,
    style_item_product_id             bigint                   not null
        constraint fk_produc
            references style_item_product,
    range_plan_quantity               bigint                   not null,
    mrp_per_pc_value                  numeric                  not null,
    mrp_value                         numeric                  not null,
    cpu_per_pc_value                  numeric                  not null,
    cpu_value                         numeric                  not null,
    priority_id                       bigint                   not null,
    prev_year_quantity                bigint,
    prev_year_efficiency              numeric,
    added_by                          bigint                   not null,
    updated_by                        bigint,
    date_added                        timestamp with time zone not null,
    date_updated                      timestamp with time zone,
    range_plan_details_size_list_json json,
    size_list                         json
);

alter table tran_range_plan_details
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_range_plan_details to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_range_plan_details to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_range_plan_details to service_role;

