create table tran_pre_costing
(
    tran_pre_costing_id               bigint generated by default as identity
        constraint tran_pre_costing_id_pkey
            primary key,
    tran_sample_order_id              bigint                   not null
        constraint fk_detl
            references tran_sample_order,
    pre_costing_date                  timestamp with time zone not null,
    total_raw_material_cost           numeric,
    total_raw_material_percentage     numeric,
    factory_overhead_cost             numeric,
    sales_marketing_distribution_cost numeric,
    depreciation_amortization_cost    numeric,
    total_overhead_cost               numeric,
    total_production_cost             numeric,
    floor_price_percentage            numeric,
    floor_price_per_pc                numeric,
    desired_markup_percentage         numeric,
    estimated_markup_price            numeric,
    desired_markup_price              numeric,
    final_mrp                         numeric,
    total_style_quantity_mrp          numeric,
    suggested_mrp_with_cost           numeric,
    smv                               text,
    remarks                           text,
    added_by                          bigint                   not null,
    date_added                        timestamp with time zone not null,
    updated_by                        bigint,
    date_updated                      timestamp with time zone,
    color_wise_size_quantity          json,
    pre_costing_quantity              bigint
);

alter table tran_pre_costing
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_pre_costing to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_pre_costing to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_pre_costing to service_role;

