create table tran_va_plan_detl_style_color_size
(
    tran_va_plan_detl_style_color_size_id bigint generated by default as identity
        primary key,
    tran_va_plan_detl_style_color_id      bigint                                 not null
        constraint fk_delt
            references tran_va_plan_detl_style_color
            on delete cascade,
    style_product_size_group_detid        bigint                                 not null
        constraint fk_sizegroup_detl
            references style_product_size_group_details,
    style_color_size_quantity             bigint                                 not null,
    added_by                              bigint                                 not null,
    updated_by                            bigint,
    date_added                            timestamp with time zone default now() not null,
    date_updated                          timestamp with time zone
);

alter table tran_va_plan_detl_style_color_size
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_va_plan_detl_style_color_size to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_va_plan_detl_style_color_size to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_va_plan_detl_style_color_size to service_role;

