create table tran_tech_pack_embellishment_det
(
    tran_tech_pack_embellishment_det_id  bigint generated by default as identity
        constraint tran_tech_pack_embellishment_det_id_pkey
            primary key,
    tran_tech_pack_embellishment_info_id bigint                   not null
        constraint fk_det
            references tran_tech_pack_embellishment_info
            on delete cascade,
    gen_garment_part_id                  bigint                   not null,
    gen_process_master_detail_id         bigint                   not null,
    color_details                        json,
    added_by                             bigint                   not null,
    updated_by                           bigint,
    date_added                           timestamp with time zone not null,
    date_updated                         timestamp with time zone
);

alter table tran_tech_pack_embellishment_det
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_tech_pack_embellishment_det to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_tech_pack_embellishment_det to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_tech_pack_embellishment_det to service_role;

