create table tran_bp_event_month
(
    tran_bp_event_month_id       bigint generated by default as identity
        constraint tran_bp_season_month_pkey
            primary key,
    tran_bp_event_id             bigint
        constraint fk_tran_bp_eventid
            references tran_bp_event
            on delete cascade,
    month_id                     bigint
        constraint tran_bp_season_month_month_id_fkey
            references month,
    monthly_gross_sales          numeric,
    added_by                     bigint                  not null,
    updated_by                   bigint,
    date_added                   timestamp default now() not null,
    date_updated                 timestamp default now(),
    event_month_outlet_list_json json
);

alter table tran_bp_event_month
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_bp_event_month to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_bp_event_month to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_bp_event_month to service_role;

