create table tran_bp_event
(
    tran_bp_event_id      bigint generated by default as identity
        constraint tbl_tran_businessplan_season_pkey
            primary key,
    event_id              bigint
        constraint fk_eventid
            references gen_season_event_config,
    event_gross_sales     numeric,
    readygoods_qnty       bigint,
    readygoods_value      numeric,
    added_by              bigint                  not null,
    updated_by            bigint,
    date_added            timestamp default now() not null,
    date_updated          timestamp default now(),
    tran_bp_year_id       bigint
        constraint fk_tran_bp_yearid
            references tran_bp_year
            on delete cascade,
    event_month_list_json json
);

alter table tran_bp_event
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_bp_event to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_bp_event to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_bp_event to service_role;

