create table tran_scm_fabric_po_details
(
    po_details_id bigint generated by default as identity (maxvalue 2147483647),
    po_id         bigint not null,
    pr_id         bigint not null,
    item_id       bigint not null,
    item_quantity numeric,
    unit          text,
    unit_price    numeric,
    total_price   numeric,
    remarks       text
);

alter table tran_scm_fabric_po_details
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_scm_fabric_po_details to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_scm_fabric_po_details to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_scm_fabric_po_details to service_role;

