create table tran_tech_pack_embellishment_info
(
    tran_tech_pack_embellishment_info_id bigint generated by default as identity
        constraint tran_tech_pack_embellishment_det_pkey
            primary key,
    tran_tech_pack_id                    bigint                   not null
        constraint fk_det
            references tran_tech_pack
            on delete cascade,
    gen_process_master_id                bigint                   not null,
    supplier_id                          bigint                   not null,
    is_garment_form                      text,
    embellishment_details                json,
    added_by                             bigint                   not null,
    updated_by                           bigint,
    date_added                           timestamp with time zone not null,
    date_updated                         timestamp with time zone,
    supplier_info                        json
);

alter table tran_tech_pack_embellishment_info
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_tech_pack_embellishment_info to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_tech_pack_embellishment_info to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_tech_pack_embellishment_info to service_role;

