create table tran_tech_pack
(
    tran_techpack_id             bigint generated by default as identity
        primary key,
    tran_designer_review_id      bigint                                 not null
        constraint fk_review
            references tran_designer_review
            on delete cascade,
    techpack_number              text,
    techpack_date                timestamp with time zone,
    costing_smv                  numeric,
    teckpack_style_code          text,
    aop_style                    text,
    merchandiser_id              bigint
        constraint fk_merchant
            references gen_team_members,
    production_availability_path text,
    vat                          text,
    photoshoot                   text,
    e_com                        text,
    sample_ok                    text,
    follow_style                 text,
    need_production_approval     text,
    iron                         text,
    fabric_allocation            text,
    additional_comments          text,
    photos                       json,
    size_details                 json,
    is_submitted                 boolean,
    is_approved                  boolean,
    approved_by                  bigint,
    approve_date                 timestamp with time zone,
    approve_remarks              text,
    added_by                     bigint                                 not null,
    updated_by                   bigint,
    date_added                   timestamp with time zone default now() not null,
    date_updated                 timestamp with time zone default now(),
    color_wise_size_quantity     json,
    tech_pack_costing_quantity   bigint
);

alter table tran_tech_pack
    owner to postgres;

create trigger set_techpack_serial_number
    before insert
    on tran_tech_pack
    for each row
execute procedure generate_techpack_serial_number();

grant delete, insert, references, select, trigger, truncate, update on tran_tech_pack to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_tech_pack to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_tech_pack to service_role;

