create sequence tran_va_plan_detl_style_color_tran_va_plan_detl_style_color_seq
    maxvalue 2147483647;

alter sequence tran_va_plan_detl_style_color_tran_va_plan_detl_style_color_seq owner to postgres;

alter sequence tran_va_plan_detl_style_color_tran_va_plan_detl_style_color_seq owned by tran_va_plan_detl_style_color.tran_va_plan_detl_style_color_id;

grant select, update, usage on sequence tran_va_plan_detl_style_color_tran_va_plan_detl_style_color_seq to anon;

grant select, update, usage on sequence tran_va_plan_detl_style_color_tran_va_plan_detl_style_color_seq to authenticated;

grant select, update, usage on sequence tran_va_plan_detl_style_color_tran_va_plan_detl_style_color_seq to service_role;

