create table tran_scm_pr_acknowledge
(
    pr_acknowledge_id   bigint generated by default as identity (maxvalue 2147483647),
    pr_no               text,
    pr_type             text,
    is_submitted        boolean,
    acknowledge_by      bigint,
    acknowledge_date    timestamp with time zone,
    acknowledge_remarks text,
    documents           json,
    added_by            bigint                                 not null,
    updated_by          bigint,
    date_added          timestamp with time zone default now() not null,
    date_updated        timestamp with time zone
);

alter table tran_scm_pr_acknowledge
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_scm_pr_acknowledge to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_scm_pr_acknowledge to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_scm_pr_acknowledge to service_role;

