create table tran_pre_costing_item_subcontract_detail
(
    tran_pre_costing_item_subcontract_detail_id bigint generated by default as identity
        constraint tran_pre_costing_item_subcontract_detail_id_pkey
            primary key,
    tran_pre_costing_id                         bigint                   not null
        constraint fk_detl
            references tran_pre_costing
            on delete cascade,
    process_master_id                           bigint
        constraint fk_process
            references gen_process_master,
    measurement_unit_detail_id                  bigint                   not null
        constraint fk_measurement
            references gen_measurement_unit_detail,
    order_quantity                              numeric                  not null,
    wastage                                     numeric,
    total_order_quantity                        numeric                  not null,
    price_per_unit                              numeric,
    total_price                                 numeric,
    remarks                                     text,
    added_by                                    bigint                   not null,
    date_added                                  timestamp with time zone not null,
    updated_by                                  bigint,
    date_updated                                timestamp with time zone
);

alter table tran_pre_costing_item_subcontract_detail
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_pre_costing_item_subcontract_detail to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_pre_costing_item_subcontract_detail to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_pre_costing_item_subcontract_detail to service_role;

