create table tran_scm_bill_submission
(
    bill_submission_id           bigint generated by default as identity (maxvalue 2147483647),
    po_id                        bigint                                 not null,
    supplier_id                  bigint                                 not null,
    challan_no                   bigint                                 not null,
    challan_date                 timestamp with time zone default now() not null,
    bill_date                    timestamp with time zone default now() not null,
    total_po_amount              numeric,
    loading_cost_in_percentage   numeric,
    loading_cost                 numeric,
    transport_cost_in_percentage numeric,
    transport_cost               numeric,
    discount_in_percentage       numeric,
    discount_amount              numeric,
    vat_in_percentage            numeric,
    vat_amount                   numeric,
    total_value                  numeric,
    is_submitted                 boolean,
    status                       integer,
    documents                    json,
    remarks                      text
);

alter table tran_scm_bill_submission
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_scm_bill_submission to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_scm_bill_submission to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_scm_bill_submission to service_role;

