create table tran_range_plan
(
    range_plan_id                bigint generated by default as identity
        primary key,
    tran_bp_year_id              bigint
        constraint fk_tran_bp_year
            references tran_bp_year,
    remarks                      text,
    added_by                     bigint                                 not null,
    updated_by                   bigint,
    date_added                   timestamp with time zone default now() not null,
    date_updated                 timestamp with time zone,
    is_submitted                 boolean,
    is_approved                  boolean,
    approved_by                  bigint,
    approve_date                 timestamp with time zone,
    approve_remarks              text,
    range_plan_details_list_json json
);

alter table tran_range_plan
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_range_plan to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_range_plan to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_range_plan to service_role;

