create table tran_bp_event_month_outlet
(
    tran_bp_event_month_outlet_id bigint generated by default as identity
        constraint tran_bp_season_month_outlet_pkey
            primary key,
    tran_bp_event_month_id        bigint
        constraint fk_tran_bp_event_monthid
            references tran_bp_event_month
            on delete cascade,
    outlet_id                     bigint
        constraint fk_outletid
            references gen_outlet,
    outlet_gross_sales            numeric,
    added_by                      bigint                  not null,
    updated_by                    bigint,
    date_added                    timestamp default now() not null,
    date_updated                  timestamp default now()
);

alter table tran_bp_event_month_outlet
    owner to postgres;

grant delete, insert, references, select, trigger, truncate, update on tran_bp_event_month_outlet to anon;

grant delete, insert, references, select, trigger, truncate, update on tran_bp_event_month_outlet to authenticated;

grant delete, insert, references, select, trigger, truncate, update on tran_bp_event_month_outlet to service_role;

